name: Releases

on: 
  push: 
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.46.3
    - name:  Build
      run: deno task build
    - uses: ncipollo/release-action@v1
      with:
        # YYYYMMDD-hhmm
        tag: "$(date +%Y%m%d)-$(date +%H%M)"
        artifacts: "dist/*" 